name: Get email body for stale projects
description: HTML containing body for email

on:
  workflow_call:

inputs:
  to:
    description: Recipient email addressed (separate with comma)
    required: true

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/
        scope: '@thepolicylab-projectportals'
    - run: '''curl 'http://localhost:8003/___graphql' \
          -X POST \
          -H 'content-type: application/json' \
          --data '{
          "query": "{ allProject { 
          nodes { 
          id
          endDate
          mainContact {
            email
            name
          }
          opportunityCloses
          slug
          startDate
          status
          title
          lastModified
          } } }"
        }' --verbose'''
      id: get_projects
    - run: "echo 'found project: ${{ steps.get_projects.outputs.data }}'"
    - name: Email Body
      id: get_body
      run: |
        body=$(node ./.github/scripts/get-stale-projects.js)
        echo "body=$body" >> $GITHUB_ENV
      with:
        query: ${{ fromJSON(steps.get_projects.outputs.data) }}
    - name: Send notification email to Heather
      uses: dawidd6/action-send-mail@v2
      with:
        # mail server settings
        server_address: smtp.gmail.com
        server_port: 465
        # user credentials
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        # email subject
        subject: Conda install failure for ${{ github.repository }}
        # email body as text
        body: ${{ env.body }}
        # comma-separated string, send email to
        to: ${{ env.to }}
        # from email name
        from: Your Friendly Neighborhood Spider-man