name: Get email body for stale projects

on:
  workflow_call:
    inputs:
      to:
        type: string
        default: "heather_yu@brown.edu"

permissions:
  contents: read
  packages: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          scope: '@thepolicylab-projectportals'

      - run: yarn config set 'npmRegistries["//npm.pkg.github.com"].npmAuthToken' "${{ secrets.GITHUB_TOKEN }}"

      - run: yarn install --immutable

      - run: npm install -g pa11y-ci

      - run: yarn build

      - name: Start up app
        run: yarn serve & npx wait-on http://localhost:8003

      - run: |
          curl 'http://localhost:8003/___graphql' \
          -X POST \
          -H 'content-type: application/json' \
          --data '{
          "query": "{ allProject { nodes { id } } }"
          }' --verbose
        id: get_projects
      - run: "echo 'found project: ${{ steps.get_projects.outputs.data }}'"
      - name: Email Body
        id: get_body
        run: |
          body=$(node ./.github/scripts/get-stale-projects.js ${{ fromJSON(steps.get_projects.outputs.data) }})
          echo "body=$body" >> $GITHUB_ENV
      - name: Send notification email to Heather
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: Conda install failure for ${{ github.repository }}
          # email body as text
          body: ${{ env.body }}
          # comma-separated string, send email to
          to: ${{ inputs.to }}
          # from email name
          from: Your Friendly Neighborhood Spider-man